[package]
name = "transpiler"
version = "0.1.0"
edition = "2021"

[dependencies]
ast = { path = "../ast" }
diagnostic = { path = "../diagnostic", features = ["global_instance"] }
lazy_static = { version = "1", optional = true }

[features]
global_instance = ["lazy_static"]
